name: Deploy to heroku

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          # Heroku app details
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # Docker settings
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: |
            --no-cache
            --build-arg SNAPCHAT_USERNAME=${{ secrets.SNAPCHAT_USERNAME }}
            --build-arg TELEGRAM_API_TOKEN=${{ secrets.TELEGRAM_API_TOKEN }}
            --build-arg TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
            --build-arg DOWNLOAD_DIR=${{ secrets.DOWNLOAD_DIR }}
          
          process_type: web
