name: Deploy to Render
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Create .env file with environment variables
      - name: Create .env file
        run: |
          echo "SNAPCHAT_USERNAME=${{ secrets.SNAPCHAT_USERNAME }}" >> .env
          echo "TELEGRAM_API_TOKEN=${{ secrets.TELEGRAM_API_TOKEN }}" >> .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
          echo "DOWNLOAD_DIR=${{ secrets.DOWNLOAD_DIR }}" >> .env
          echo "WEB_SECRET_KEY=${{ secrets.WEB_SECRET_KEY }}" >> .env
          echo "WEB_USERNAME=${{ secrets.WEB_USERNAME }}" >> .env
          echo "WEB_PASSWORD=${{ secrets.WEB_PASSWORD }}" >> .env
          echo "REPO_URL_WITH_TOKEN=${{ secrets.REPO_URL_WITH_TOKEN }}" >> .env
          echo "REPO_BRANCH=${{ secrets.REPO_BRANCH }}" >> .env

      - name: Upload .env file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env
          
      # Step 3: Deploy to Render
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }} # Find this in Render dashboard URL
          api-key: ${{ secrets.RENDER_API_KEY }}       # Get this from Render dashboard