name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_APP_NAME }}
          usedocker: true
          docker_build_args: |
            SNAPCHAT_USERNAME
            TELEGRAM_API_TOKEN
            TELEGRAM_CHAT_ID
            DOWNLOAD_DIR
        env:
          SNAPCHAT_USERNAME: ${{ secrets.SNAPCHAT_USERNAME }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DOWNLOAD_DIR: ${{ secrets.DOWNLOAD_DIR }}