name: Deploy to heroku

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Create .env file with environment variables from GitHub Secrets
      - name: Create .env file
        run: |
          echo "SNAPCHAT_USERNAME=${{ secrets.SNAPCHAT_USERNAME }}" >> .env
          echo "TELEGRAM_API_TOKEN=${{ secrets.TELEGRAM_API_TOKEN }}" >> .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
          echo "DOWNLOAD_DIR=${{ secrets.DOWNLOAD_DIR }}" >> .env

      # Step 3: Set Heroku stack to 'container'
      - name: Set Heroku stack to container
        run: |
          echo "Setting Heroku stack to container..."
          heroku stack:set container --app ${{ secrets.HEROKU_APP_NAME }}

      # Step 4: Build, Push and Release a Docker container to Heroku
      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          process_type: web
